# permissions for end users to view blueprints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blueprint-viewer-role
rules:
- apiGroups:
  - operators.coreos.com.operator-manager.domain
  resources:
  - blueprints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com.operator-manager.domain
  resources:
  - blueprints/status
  verbs:
  - get
