# permissions for end users to view installplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installplan-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - installplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - installplans/status
  verbs:
  - get
