# permissions for end users to view subscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscription-viewer-role
rules:
- apiGroups:
  - operators.coreos.com.operator-manager.domain
  resources:
  - subscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com.operator-manager.domain
  resources:
  - subscriptions/status
  verbs:
  - get
